name: CI/CD PIPELINE TO BUILD AND DEPLOY TO TOMCAT
on:
   push:
     branches: 
      - master
   workflow_dispatch:
   
jobs:
     build:
       runs-on: ubuntu-latest
       
       steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: Set up Java
          uses: actions/setup-java@v4
          with:
           distribution: temurin
           java-version: '17'
           cache: maven

        - name: Check Java
          run: java -version

        - name: Check Maven
          run: mvn -version 
         
        - name: validate with maven
          run: mvn validate
        - name: compile with maven
          run: mvn compile
        - name: test with maven
          run: mvn test
        - name: package with maven
          run: mvn package
        - name: verify war file
          run: ls -lh target/

        - name: Deploy WAR to Tomcat
          run: |
            curl -v \
            -u "${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }}" \
            -T "target/TrainBook-1.0.0-SNAPSHOT.war" \
            "http://${{ secrets.TOMCAT_HOST }}:8080/manager/text/deploy?path=/TrainBook&update=true"
            
        - name: Deploy WAR file to DEV Tomcat
          run: |
            curl -v \
            -u "${{ secrets.TOMCAT_DEV_USER }}:${{ secrets.TOMCAT_DEV_PASSWORD }}" \
            -T "target/TrainBook-1.0.0-SNAPSHOT.war" \
            "http://${{ secrets.TOMCAT_DEV_HOST }}:8080/manager/text/deploy?path=/TrainBook&update=true"
            
        - name: Deploy WAR file to TEST to Tomcat
          run: |
            curl -v \
            -u "${{ secrets.TOMCAT_TEST_USER }}:${{ secrets.TOMCAT_TEST_PASSWORD }}" \
            -T "target/TrainBook-1.0.0-SNAPSHOT.war" \
            "http://${{ secrets.TOMCAT_TEST_HOST }}:8080/manager/text/deploy?path=/TrainBook&update=true"
            
        - name: Deploy WAR file to PREPOD toTomcat
          run: |
            curl -v \
            -u "${{ secrets.TOMCAT_PREPOD_USER }}:${{ secrets.TOMCAT_PREPOD_PASSWORD }}" \
            -T "target/TrainBook-1.0.0-SNAPSHOT.war" \
            "http://${{ secrets.TOMCAT_PREPOD_HOST }}:8080/manager/text/deploy?path=/TrainBook&update=true"

        - name: Deploy WAR file to PROD to Tomcat
          run: |
            curl -v \
            -u "${{ secrets.TOMCAT_PROD_USER }}:${{ secrets.TOMCAT_PROD_PASSWORD }}" \
            -T "target/TrainBook-1.0.0-SNAPSHOT.war" \
            "http://${{ secrets.TOMCAT_PROD_HOST }}:8080/manager/text/deploy?path=/TrainBook&update=true"

          
